# Basic Python

## 1. Split this string

In [2]:
s = "Hi there Sam!"

In [3]:
x = s.split()
print(x)

['Hi', 'there', 'Sam!']


## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [7]:
planet = "Earth"
diameter = 12742

In [6]:
txt = "The diamete of {planet} is {diameter} kilometers"
print(txt.format(planet = "Earth", diameter = 12742))

The diamete of Earth is 12742 kilometers


## 3. In this nest dictionary grab the word "hello"

In [28]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [40]:
print(d['k1'][3]['tricky'][3]['target'][3])

hello


# Numpy

In [ ]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [8]:
arr=[]
arr = [0 for i in range(10)] 
print(arr)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]


In [10]:
arr=[]
arr = [5 for i in range(10)] 
print(arr)

[5, 5, 5, 5, 5, 5, 5, 5, 5, 5]


## 5. Create an array of all the even integers from 20 to 35

In [12]:
import numpy as np
array=np.arange(20,35,2)
print(array)

[20 22 24 26 28 30 32 34]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [18]:
import numpy as np
x =  np.arange(0,9).reshape(3,3)
print(x)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [27]:
import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
  
join = np.concatenate((arr1, arr2), axis = 0)
  
print (join)

[1 2 3 4 5 6]


# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [21]:
import pandas as pd


In [22]:
data = [['tom', 10], ['nick', 15], ['juli', 14]]

df = pd.DataFrame(data, columns=['Name', 'Age'])
  
df


Name  Age
0   tom   10
1  nick   15
2  juli   14

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [26]:
import numpy as np
print(np.arange('2023-01', '2023-02', dtype='datetime64[D]'))

['2023-01-01' '2023-01-02' '2023-01-03' '2023-01-04' '2023-01-05'
 '2023-01-06' '2023-01-07' '2023-01-08' '2023-01-09' '2023-01-10'
 '2023-01-11' '2023-01-12' '2023-01-13' '2023-01-14' '2023-01-15'
 '2023-01-16' '2023-01-17' '2023-01-18' '2023-01-19' '2023-01-20'
 '2023-01-21' '2023-01-22' '2023-01-23' '2023-01-24' '2023-01-25'
 '2023-01-26' '2023-01-27' '2023-01-28' '2023-01-29' '2023-01-30'
 '2023-01-31']


## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [23]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [41]:
import pandas as pd
import numpy as np
arr= np.array(lists)
df=pd.DataFrame(arr)
print(df)

   0    1   2
0  1  aaa  22
1  2  bbb  25
2  3  ccc  24
